version: '3.6'
services:
  meta-node:
    container_name: meta-node
    environment:
      - GLS_CONNECTOR_PORT=3031
      - GLS_MONGO_EXTERNAL_PORT=27018
      - GLS_MONGO_CONNECT=mongodb://meta-mongo/meta
    build:
      context: https://github.com/GolosChain/meta-service.git
    ports:
      - 127.0.0.1:3031:3031
    depends_on:
      - meta-mongo
    networks:
      - services-tier
    restart: always
    
  meta-mongo:
    container_name: meta-mongo
    image: mongo:4
    ports:
      - 127.0.0.1:27018:27017
    volumes:
      - meta-mongodb-vol:/data/db
    networks:
      - services-tier
    restart: always

  options-node:
    container_name: options-node
    environment:
      - GLS_CONNECTOR_PORT=3032
      - GLS_MONGO_EXTERNAL_PORT=27019
      - GLS_MONGO_CONNECT=mongodb://options-mongo/options
    build:
      context: https://github.com/GolosChain/options-service.git
    ports:
      - 127.0.0.1:3032:3032
    depends_on:
      - options-mongo
    networks:
      - services-tier
    restart: always

  options-mongo:
    container_name: options-mongo
    image: mongo:4
    ports:
      - 127.0.0.1:27019:27017
    volumes:
      - options-mongodb-vol:/data/db
    networks:
      - services-tier 
    restart: always

  auth-node:
    container_name: auth-node
    environment:
      - GLS_CONNECTOR_PORT=3033
      - GLS_CYBERWAY_HTTP_URL=${CYBERWAY_HTTP_URL}
    build:
      context: https://github.com/GolosChain/auth-service.git
    ports:
      - 127.0.0.1:3033:3033
    networks:
      - services-tier
    restart: always   

  gate-node:
    container_name: gate-node
    environment:
      - GLS_CONNECTOR_PORT=3002
      - GLS_AUTH_CONNECT=http://auth-node:3033
      - GLS_FACADE_CONNECT=http://facade-node:3001
    build:
      context: https://github.com/GolosChain/gate-service.git
    ports:
      - 0.0.0.0:8080:8080
      - 127.0.0.1:3002:3002
    networks:
      - services-tier
    restart: always
  
  wallet:
    container_name: wallet-node
    environment:
      - GLS_CONNECTOR_PORT=3040
      - GLS_MONGO_EXTERNAL_PORT=27020
      - GLS_MONGO_CONNECT=mongodb://wallet-mongo/wallet
      - GLS_VERBOSE_LOGS=true
      - GLS_BLOCKCHAIN_BROADCASTER_SERVER_NAME=cyberway
      - GLS_BLOCKCHAIN_BROADCASTER_CLIENT_NAME=wallet-1
      - GLS_BLOCKCHAIN_BROADCASTER_CONNECT=${BLOCKCHAIN_BROADCASTER_URL}
      - GLS_CYBERWAY_HTTP_URL=${CYBERWAY_HTTP_URL}
    build: 
      context: https://github.com/GolosChain/wallet-service.git
    ports:
      - 127.0.0.1:3040:3040
    depends_on:
      - wallet-mongo
    networks:
      - services-tier
    restart: always
  
  wallet-mongo:
    container_name: wallet-mongo
    image: mongo:4
    ports:
      - 127.0.0.1:27020:27017
    volumes:
      - wallet-mongodb-vol:/data/db
    networks:
      - services-tier 
    restart: always
    
  prism-node:
    container_name: prism-node
    environment:
      - GLS_CONNECTOR_PRISM_PORT=3039
      - GLS_MONGO_EXTERNAL_PORT=27021
      - GLS_MONGO_CONNECT=mongodb://prism-mongo/prism
      - GLS_BLOCKCHAIN_BROADCASTER_SERVER_NAME=cyberway
      - GLS_BLOCKCHAIN_BROADCASTER_CLIENT_NAME=prism-1
      - GLS_BLOCKCHAIN_BROADCASTER_CONNECT=${BLOCKCHAIN_BROADCASTER_URL}
      - GLS_CYBERWAY_CONNECT=${CYBERWAY_HTTP_URL}
      - GLS_BLOCK_SUBSCRIBER_REPLAY_TIME_DELTA=600000
      - GLS_BLOCK_SUBSCRIBER_CLEANER_INTERVAL=600000
      - GLS_BLOCK_SUBSCRIBER_LAST_BLOCK_STORE=1000
      - GLS_SEARCH_CONNECTION_STRING=http://elasticsearch:9200
      - GLS_EXPORT_GOLOS_USERS=false
      - GLS_SAVE_GENESIS_EXAMPLES=false
      - GLS_SKIP_MISSING_TRANSACTIONS=false
      - GLS_ENABLE_BLOCK_HANDLE=true
      - GLS_ENABLE_PUBLIC_API=false
    build: 
      context: https://github.com/GolosChain/prism-service.git
    ports:
      - 127.0.0.1:3039:3039
    depends_on:
      - prism-mongo
      - elasticsearch
    networks:
      - services-tier
    restart: always

  prism-node-api:
    container_name: prism-node-api
    environment:
      - GLS_CONNECTOR_PORT=3036
      - GLS_MONGO_EXTERNAL_PORT=27021
      - GLS_MONGO_CONNECT=mongodb://prism-mongo/prism
      - GLS_SEARCH_CONNECTION_STRING=http://elasticsearch:9200
      - GLS_EXPORT_GOLOS_USERS=false
      - GLS_SAVE_GENESIS_EXAMPLES=false
      - GLS_SKIP_MISSING_TRANSACTIONS=false
      - GLS_ENABLE_BLOCK_HANDLE=false
      - GLS_ENABLE_PUBLIC_API=true
      - GLS_SEARCH_ENABLED=false
    build: 
      context: https://github.com/GolosChain/prism-service.git
    ports:
      - 127.0.0.1:3036:3036
    depends_on:
      - prism-mongo
      - elasticsearch
    networks:
      - services-tier
    restart: always

  prism-mongo:
    container_name: prism-mongo
    image: mongo:4
    ports:
      - 127.0.0.1:27021:27017
    volumes:
      - prism-mongodb-vol:/data/db
    networks:
      - services-tier 
    restart: always

  elasticsearch:
    container_name: elasticsearch
    environment:
      'discovery.type': 'single-node'
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - services-tier
  
  facade-node:
    container_name: facade-node
    environment:
      - GLS_CONNECTOR_PORT=3001
      - GLS_META_CONNECT=http://meta-node:3031
      - GLS_OPTIONS_CONNECT=http://options-node:3032
      - GLS_FRONTEND_GATE_CONNECT=http://gate-node:3034
      - GLS_WALLET_CONNECT=http://wallet-node:3040
      - GLS_PRISM_CONNECT=http://prism-node:3039
      - GLS_PRISM_API_CONNECT=http://prism-node-api:3036
      - GLS_BANDWIDTH_PROVIDER_CONNECT=http://bandwidth-provider-node:3037
      - GLS_FRONTEND_GATE_CONNECT=http://gate-node:3002
    build: 
      context: https://github.com/GolosChain/facade-service.git#develop
    ports:
      - 0.0.0.0:3001:3001
    networks:
      - services-tier
    restart: always

  bandwidth-provider:
    container_name: bandwidth-provider-node
    environment:
      - GLS_CONNECTOR_PORT=3037
      - GLS_MONGO_EXTERNAL_PORT=27022
      - GLS_MONGO_CONNECT=mongodb://bandwidth-provider-mongo/bandwidth
      - GLS_CYBERWAY_HTTP_URL=${CYBERWAY_HTTP_URL}
      - GLS_PROVIDER_PUBLIC_KEY=${GLS_PROVIDER_PUBLIC_KEY}
      - GLS_PROVIDER_WIF=${GLS_PROVIDER_WIF}
      - GLS_PROVIDER_USERNAME=${GLS_PROVIDER_USERNAME}
      - GLS_PRISM_CONNECT=http://prism-node:3039
    build: 
      context: https://github.com/GolosChain/bandwidth-service.git
    ports:
      - 127.0.0.1:3037:3037
    depends_on:
      - bandwidth-provider-mongo
    networks:
      - services-tier
    restart: always
  
  bandwidth-provider-mongo:
    container_name: bandwidth-provider-mongo
    image: mongo:4
    ports:
      - 127.0.0.1:27022:27017
    volumes:
      - bandwidth-mongodb-vol:/data/db
    networks:
      - services-tier 
    restart: always

volumes:
  meta-mongodb-vol:
  options-mongodb-vol:
  wallet-mongodb-vol:
  prism-mongodb-vol:
  bandwidth-mongodb-vol:

networks:
  services-tier:

